# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumCreator', '0002_auto_20160227_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug_owner_name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_location',
            field=models.ImageField(blank=True, upload_to='/photos/'),
        ),
    ]
