# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumCreator', '0003_auto_20160227_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='like_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
