# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumCreator', '0005_auto_20160227_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='stored_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='url_name'),
        ),
    ]
