# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumCreator', '0007_auto_20160228_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_location',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_capacity',
            field=models.IntegerField(default=501),
        ),
        migrations.AlterField(
            model_name='photo',
            name='stored_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 28, 17, 28, 25, 890042), null=True),
        ),
    ]
