# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumCreator', '0008_auto_20160228_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='stored_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 28, 17, 29, 36, 729407), null=True),
        ),
    ]
